<?xml version="1.0"?>
<package format="2">
  <name>multipoint</name>
  <version>0.1.0</version>
  <description>Waypoint mission controller with SIYI A8 mini Ethernet gimbal coordination.</description>

  <maintainer email="cky@todo.todo">cky</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>mavros_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>quadrotor_msgs</depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>

  <export/>
</package>
